import { Request, Response, NextFunction } from "express";
import { ApiError } from "../utils/ApiError";

export const errorHandler = (
  err: Error | ApiError,
  req: Request,
  res: Response,
  next: NextFunction
): void => {
  console.error(err);

  if (err instanceof ApiError) {
    res.status(err.statusCode).json({
      error: {
        code: err.code,
        message: err.message,
        ...(err.details && { details: err.details }), 
      },
    });
  } else {
    res.status(500).json({
      error: {
        code: "INTERNAL_SERVER_ERROR",
        message: "Ocurri√≥ un error interno en el servidor.",
      },
    });
  }
};
